Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.define "ubuntu_minikube" do |ubuntu_minikube|
    config.vm.network "forwarded_port", 
      guest: 8001, 
      host:  8001, 
      auto_correct: true
    config.vm.provider "virtualbox" do |vb|
      vb.name = "Ubuntu Minikube"
      vb.memory = "4096"
      vb.cpus = "1"
    config.vm.provision "shell",
      path: "setup/docker.sh",
      args: []
    config.vm.provision "shell",
      path: "setup/minikube.sh",
      args: []  
    config.vm.provision "shell",
      path: "setup/kubectl.sh",
      args: []
    end
  end
end